apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-example
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/pvdata"
