apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh","-c","while true; do sleep 3600; done"]
    volumeMounts:
    - name: custom-volume
      mountPath: /tmp/storage
  volumes:
  - name: custom-volume
    emptyDir: {}
