---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-deployment
  annotations:
    fluxcd.io/tag.nginx: semver:~1.0
    fluxcd.io/automated: "true"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - containerPort: 80

