apiVersion: v1
kind: Pod
metadata:
  name: candy-service-pod
spec:
  serviceAccountName: candy-svc
  securityContext:
    fsGroup: 2000
  containers:
  - name: candy-service
    image: linuxacademycontent/candy-service:1
    volumeMounts:
      - name: candy-service-config-vol
        mountPath: /etc/candy-service
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-password
          key: password
  volumes:
    - name: candy-service-config-vol
      configMap:
        name: candy-service-config
