apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  namespace: ckad
  labels:
    app: configmap-pod
spec:
  containers:
  - name: configmap-pod
    image: busybox
    command: ["sh", "-c", "echo $(CONFIGMAP_KEY1) && sleep 3600"]
    env:
    - name: CONFIGMAP_KEY1
      valueFrom:
        configMapKeyRef: 
          name: example-configmap
          key: my-key
    - name: CONFIGMAP_KEY2
      valueFrom:
        configMapKeyRef:
          name: example-configmap
          key: another-key
  
