apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-pod
    image: mysql:5.6
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    volumeMounts:
    - name: pvc-volume
      mountPath: "/var/lib/mysql"
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: mysql-pv-claim
