apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
  - name: busybox-pvc
    image: busybox
    command: ["sh", "-c","while true; do sleep 3600; done"]
    volumeMounts:
    - name: pvc-volume
      mountPath: "/mnt/storage"
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: mypvc
