apiVersion: v1
kind: Pod
metadata:
  name: readinessprobe-pod
spec:
  containers:
  - name: readinessprobe-container
    image: nginx
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      httpGet:
        path: / 
        port: 80
