apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
  namespace: ckad
  labels:
    app: pod-uses-sa
spec:
  serviceAccountName: dev-specific-sa
  containers:
  - name: sa-pod
    image: busybox
    command: ["sh", "-c", "echo this pod uses dev-specific-sa to communicate with kube api-server && sleep 3600"]
