apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: ckad
  labels:
    app: secret-pod
spec:
  containers:
  - name: secret-pod
    image: busybox
    command: ["sh", "-c", "echo login details are username:$(USERNAME), password:$(PASSWORD) && sleep 3600"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef: 
          name: my-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
  
