apiVersion: v1
kind: Pod
metadata:
  name: secure-app-client
  labels:
    allow-secure-access: "true"
spec:
  containers:
  - name: secure-app-client
    image: radial/busyboxplus:curl
    command: ["sh", "-c", "while true; do sleep 3600; done"]
